### ISSUE TITLE
Specify licence

### ISSUE THREAD

**Issue by sbrt** [r-lib/jose#18]
Hallo,

Would it be possible that you choose one of the canonical licences for this package?

Best,
Sebastian

**Comment by jeroen** [comment]
It uses MIT: https://github.com/r-lib/jose/blob/429a463add39ed3329b2b7d6ac71e6a6e68d66f6/DESCRIPTION#L12

**Comment by sbrt** [comment]
Thanks for pointing that out, I just checked the LICENSE file.
